import {
  RiArticleFill,
  RiAttachmentFill,
  RiBarcodeBoxFill,
  RiBuilding2Fill,
  RiBuilding4Fill,
  RiCalculatorFill,
  RiCalendarFill,
  RiCharacterRecognitionFill,
  RiCheckboxBlankFill,
  RiCheckboxMultipleFill,
  RiDatabase2Fill,
  RiFileCopyFill,
  RiFileTextFill,
  RiImageFill,
  RiLayoutColumnFill,
  RiLinksFill,
  RiMapPinFill,
  RiMenuFill,
  RiNavigationFill,
  RiNumbersFill,
  RiQuillPenFill,
  RiRadioButtonFill,
  RiSearchFill,
  RiSmartphoneFill,
  RiSubtractFill,
  RiTableAltFill,
  RiTeamFill,
  RiUserFill,
} from '@remixicon/vue';
import type { Component } from 'vue';
import type { FormFieldType } from '../schema';

/** 仅供设计器字段清单展示，图标不会写入可持久化的表单 Schema。 */
export const formFieldIcons: Record<FormFieldType, Component> = {
  'single-line-text': RiFileTextFill,
  'multi-line-text': RiArticleFill,
  number: RiNumbersFill,
  'date-time': RiCalendarFill,
  'radio-group': RiRadioButtonFill,
  'checkbox-group': RiCheckboxMultipleFill,
  select: RiMenuFill,
  'multi-select': RiCheckboxMultipleFill,
  member: RiUserFill,
  members: RiTeamFill,
  department: RiBuilding2Fill,
  departments: RiBuilding4Fill,
  divider: RiSubtractFill,
  tabs: RiLayoutColumnFill,
  image: RiImageFill,
  attachment: RiAttachmentFill,
  address: RiMapPinFill,
  location: RiNavigationFill,
  'sub-form': RiTableAltFill,
  query: RiSearchFill,
  'data-selector': RiDatabase2Fill,
  signature: RiQuillPenFill,
  'serial-number': RiBarcodeBoxFill,
  mobile: RiSmartphoneFill,
  'text-recognition': RiCharacterRecognitionFill,
  button: RiCheckboxBlankFill,
  formula: RiCalculatorFill,
  'rich-text': RiArticleFill,
  'related-data': RiLinksFill,
  'related-query': RiSearchFill,
  'related-form': RiFileCopyFill,
};
