import type { FormulaFunction, FormulaFunctionCategory } from './types';

export const FORMULA_CATEGORY_LABELS: Readonly<Record<FormulaFunctionCategory, string>> = {
  logic: '逻辑函数',
  math: '数学函数',
  text: '文本函数',
  date: '日期函数',
  advanced: '高级函数',
};

type FunctionSeed = Omit<FormulaFunction, 'category'>;

function defineFunctions(
  category: FormulaFunctionCategory,
  functions: readonly FunctionSeed[],
): readonly FormulaFunction[] {
  return functions.map((item) => ({ ...item, category }));
}

/**
 * 前端公式目录。名称、参数个数及语法以产品公式规范为准；编辑器、函数库和静态
 * 分析器全部消费这一份目录，避免出现“列表能选、补全不能识别”的漂移。
 *
 * 前端仅用于设计期体验。提交时的权威执行与上下文函数校验仍应由未来服务端引擎接管。
 */
export const FORMULA_FUNCTIONS: readonly FormulaFunction[] = [
  ...defineFunctions('logic', [
    {
      name: 'AND',
      description: '全部条件成立时返回真',
      syntax: 'AND(logical1, logical2, ...)',
      returnType: 'boolean',
      minArgs: 1,
    },
    { name: 'FALSE', description: '返回假', syntax: 'FALSE()', returnType: 'boolean', arity: [0] },
    {
      name: 'IF',
      description: '按条件返回不同结果',
      syntax: 'IF(logical, value_if_true, value_if_false)',
      returnType: 'unknown',
      arity: [3],
    },
    {
      name: 'IFS',
      description: '按多组条件返回结果',
      syntax: 'IFS(logical1, value1, ...)',
      returnType: 'unknown',
      minArgs: 2,
    },
    {
      name: 'NOT',
      description: '返回逻辑反值',
      syntax: 'NOT(logical)',
      returnType: 'boolean',
      arity: [1],
    },
    {
      name: 'OR',
      description: '任一条件成立时返回真',
      syntax: 'OR(logical1, logical2, ...)',
      returnType: 'boolean',
      minArgs: 1,
    },
    { name: 'TRUE', description: '返回真', syntax: 'TRUE()', returnType: 'boolean', arity: [0] },
    {
      name: 'XOR',
      description: '逻辑异或判断',
      syntax: 'XOR(logical1, logical2, ...)',
      returnType: 'boolean',
      minArgs: 2,
    },
  ]),
  ...defineFunctions('text', [
    {
      name: 'CONCATENATE',
      description: '合并多个文本',
      syntax: 'CONCATENATE(text1, text2, ...)',
      returnType: 'text',
      minArgs: 1,
    },
    {
      name: 'CHAR',
      description: '按字符编码返回字符',
      syntax: 'CHAR(number)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'EXACT',
      description: '区分大小写比较文本',
      syntax: 'EXACT(text1, text2)',
      returnType: 'boolean',
      arity: [2],
    },
    {
      name: 'IP',
      description: '获取当前客户端 IP',
      syntax: 'IP()',
      returnType: 'text',
      arity: [0],
    },
    {
      name: 'ISEMPTY',
      description: '判断值是否为空',
      syntax: 'ISEMPTY(value)',
      returnType: 'boolean',
      arity: [1],
    },
    {
      name: 'JOIN',
      description: '按分隔符连接数组',
      syntax: 'JOIN(array, delimiter)',
      returnType: 'text',
      arity: [2],
    },
    {
      name: 'LEFT',
      description: '从左侧截取文本',
      syntax: 'LEFT(text, [num_chars])',
      returnType: 'text',
      minArgs: 1,
      maxArgs: 2,
    },
    {
      name: 'LEN',
      description: '返回文本长度',
      syntax: 'LEN(text)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(text)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'MID',
      description: '截取指定位置文本',
      syntax: 'MID(text, start_num, num_chars)',
      returnType: 'text',
      arity: [3],
    },
    {
      name: 'REPLACE',
      description: '替换指定位置文本',
      syntax: 'REPLACE(old_text, start_num, num_chars, new_text)',
      returnType: 'text',
      arity: [4],
    },
    {
      name: 'REPT',
      description: '重复文本',
      syntax: 'REPT(text, number_times)',
      returnType: 'text',
      arity: [2],
    },
    {
      name: 'RIGHT',
      description: '从右侧截取文本',
      syntax: 'RIGHT(text, [num_chars])',
      returnType: 'text',
      minArgs: 1,
      maxArgs: 2,
    },
    {
      name: 'RMBCAP',
      description: '将金额转换为大写金额文本',
      syntax: 'RMBCAP(number)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'SEARCH',
      description: '查找文本位置',
      syntax: 'SEARCH(find_text, within_text, [start_num])',
      returnType: 'number',
      minArgs: 2,
      maxArgs: 3,
    },
    {
      name: 'SPLIT',
      description: '按分隔符拆分文本',
      syntax: 'SPLIT(text, delimiter)',
      returnType: 'array',
      arity: [2],
    },
    {
      name: 'TEXT',
      description: '按格式转换文本',
      syntax: 'TEXT(value, format_text)',
      returnType: 'text',
      arity: [2],
    },
    {
      name: 'TRIM',
      description: '清除多余空格',
      syntax: 'TRIM(text)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'UNION',
      description: '合并数组并去重',
      syntax: 'UNION(array1, array2, ...)',
      returnType: 'array',
      minArgs: 1,
    },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(text)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'VALUE',
      description: '将文本转换为数值',
      syntax: 'VALUE(text)',
      returnType: 'number',
      arity: [1],
    },
  ]),
  ...defineFunctions('math', [
    {
      name: 'ABS',
      description: '返回绝对值',
      syntax: 'ABS(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'AVERAGE',
      description: '计算算术平均值',
      syntax: 'AVERAGE(number1, number2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'CEILING',
      description: '向指定倍数舍入',
      syntax: 'CEILING(number, significance)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'COS',
      description: '计算余弦值',
      syntax: 'COS(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'COT',
      description: '计算余切值',
      syntax: 'COT(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'COUNT',
      description: '统计数值个数',
      syntax: 'COUNT(value1, value2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'COUNTIF',
      description: '按条件统计',
      syntax: 'COUNTIF(range, criteria)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'FIXED',
      description: '按小数位格式化数值',
      syntax: 'FIXED(number, [decimals], [no_commas])',
      returnType: 'text',
      minArgs: 1,
      maxArgs: 3,
    },
    {
      name: 'FLOOR',
      description: '向指定倍数舍入',
      syntax: 'FLOOR(number, significance)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'INT',
      description: '向下取整',
      syntax: 'INT(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'LARGE',
      description: '返回第 k 个最大值',
      syntax: 'LARGE(array, k)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'LOG',
      description: '计算对数',
      syntax: 'LOG(number, [base])',
      returnType: 'number',
      minArgs: 1,
      maxArgs: 2,
    },
    {
      name: 'MAX',
      description: '返回最大值',
      syntax: 'MAX(number1, number2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'MIN',
      description: '返回最小值',
      syntax: 'MIN(number1, number2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'MOD',
      description: '返回除法余数',
      syntax: 'MOD(number, divisor)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'POWER',
      description: '计算乘幂',
      syntax: 'POWER(number, power)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'PRODUCT',
      description: '计算乘积',
      syntax: 'PRODUCT(number1, number2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    { name: 'RAND', description: '返回随机数', syntax: 'RAND()', returnType: 'number', arity: [0] },
    {
      name: 'ROUND',
      description: '按位数四舍五入',
      syntax: 'ROUND(number, [num_digits])',
      returnType: 'number',
      minArgs: 1,
      maxArgs: 2,
    },
    {
      name: 'SIN',
      description: '计算正弦值',
      syntax: 'SIN(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'SMALL',
      description: '返回第 k 个最小值',
      syntax: 'SMALL(array, k)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'SQRT',
      description: '返回平方根',
      syntax: 'SQRT(number)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'SUM',
      description: '计算总和',
      syntax: 'SUM(number1, number2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'SUMIF',
      description: '按条件求和',
      syntax: 'SUMIF(range, criteria, [sum_range])',
      returnType: 'number',
      minArgs: 2,
      maxArgs: 3,
    },
    {
      name: 'SUMIFS',
      description: '按多个条件求和',
      syntax: 'SUMIFS(sum_range, criteria_range1, criteria1, ...)',
      returnType: 'number',
      minArgs: 3,
    },
    {
      name: 'SUMPRODUCT',
      description: '计算数组乘积之和',
      syntax: 'SUMPRODUCT(array1, array2, ...)',
      returnType: 'number',
      minArgs: 1,
    },
    {
      name: 'TAN',
      description: '计算正切值',
      syntax: 'TAN(number)',
      returnType: 'number',
      arity: [1],
    },
  ]),
  ...defineFunctions('date', [
    {
      name: 'DATE',
      description: '构造或转换日期对象',
      syntax: 'DATE(timestamp) / DATE(year, month, day[, hour, minute, second])',
      returnType: 'date',
      arity: [1, 3, 6],
    },
    {
      name: 'DATEDIF',
      description: '计算日期间隔',
      syntax: 'DATEDIF(start_date, end_date, unit)',
      returnType: 'number',
      arity: [3],
    },
    {
      name: 'DATEDELTA',
      description: '按偏移量调整日期',
      syntax: 'DATEDELTA(date, delta)',
      returnType: 'date',
      arity: [2],
    },
    {
      name: 'DAY',
      description: '返回日期中的日',
      syntax: 'DAY(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'DAYS',
      description: '计算两个日期相差天数',
      syntax: 'DAYS(end_date, start_date)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'DAYS360',
      description: '按 360 天年度计算天数',
      syntax: 'DAYS360(start_date, end_date, [method])',
      returnType: 'number',
      minArgs: 2,
      maxArgs: 3,
    },
    {
      name: 'HOUR',
      description: '返回小时',
      syntax: 'HOUR(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'ISOWEEKNUM',
      description: '返回 ISO 周序号',
      syntax: 'ISOWEEKNUM(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'MINUTE',
      description: '返回分钟',
      syntax: 'MINUTE(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'MONTH',
      description: '返回月份',
      syntax: 'MONTH(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'NETWORKDAYS',
      description: '计算工作日数',
      syntax: 'NETWORKDAYS(start_date, end_date, [holidays])',
      returnType: 'number',
      minArgs: 2,
      maxArgs: 3,
    },
    { name: 'NOW', description: '返回当前时间', syntax: 'NOW()', returnType: 'date', arity: [0] },
    {
      name: 'SECOND',
      description: '返回秒数',
      syntax: 'SECOND(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'SYSTIME',
      description: '返回服务端时间',
      syntax: 'SYSTIME()',
      returnType: 'date',
      arity: [0],
    },
    {
      name: 'TIME',
      description: '构造一天中的时间值',
      syntax: 'TIME(hour, minute, second)',
      returnType: 'number',
      arity: [3],
    },
    {
      name: 'TIMESTAMP',
      description: '日期对象转换为时间戳',
      syntax: 'TIMESTAMP(date)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'TODAY',
      description: '返回当前日期',
      syntax: 'TODAY()',
      returnType: 'date',
      arity: [0],
    },
    {
      name: 'WEEKDAY',
      description: '返回星期序号',
      syntax: 'WEEKDAY(timestamp)',
      returnType: 'number',
      arity: [1],
    },
    {
      name: 'WEEKNUM',
      description: '返回一年中的周序号',
      syntax: 'WEEKNUM(timestamp, [return_type])',
      returnType: 'number',
      minArgs: 1,
      maxArgs: 2,
    },
    {
      name: 'WORKDAY',
      description: '计算工作日后的日期',
      syntax: 'WORKDAY(start_date, days, [holidays])',
      returnType: 'date',
      minArgs: 2,
      maxArgs: 3,
    },
    {
      name: 'YEAR',
      description: '返回年份',
      syntax: 'YEAR(timestamp)',
      returnType: 'number',
      arity: [1],
    },
  ]),
  ...defineFunctions('advanced', [
    {
      name: 'DISTANCE',
      description: '计算两个定位或坐标间距离',
      syntax: 'DISTANCE(location1, location2)',
      returnType: 'number',
      arity: [2],
    },
    {
      name: 'GETUSERNAME',
      description: '获取当前成员名称',
      syntax: 'GETUSERNAME()',
      returnType: 'text',
      arity: [0],
    },
    {
      name: 'INDEX',
      description: '读取数组指定位置的值',
      syntax: 'INDEX(array, position)',
      returnType: 'unknown',
      arity: [2],
    },
    {
      name: 'MAPX',
      description: '按映射规则返回值',
      syntax: 'MAPX(...)',
      returnType: 'unknown',
      minArgs: 1,
    },
    {
      name: 'RECNO',
      description: '获取当前记录序号',
      syntax: 'RECNO()',
      returnType: 'number',
      arity: [0],
    },
    {
      name: 'TEXTDEPT',
      description: '将部门值转换为文本',
      syntax: 'TEXTDEPT(department)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'TEXTLOCATION',
      description: '将定位值转换为文本',
      syntax: 'TEXTLOCATION(location)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'TEXTPHONE',
      description: '将手机号值转换为文本',
      syntax: 'TEXTPHONE(phone)',
      returnType: 'text',
      arity: [1],
    },
    {
      name: 'TEXTUSER',
      description: '将成员值转换为文本',
      syntax: 'TEXTUSER(user)',
      returnType: 'text',
      arity: [1],
    },
    { name: 'UUID', description: '生成唯一标识', syntax: 'UUID()', returnType: 'text', arity: [0] },
  ]),
];

/** 初始打开函数面板时显示的高频函数，不改变其在目录中的正式分类。 */
export const FORMULA_COMMON_FUNCTION_NAMES = [
  'CONCATENATE',
  'DATE',
  'DATEDIF',
  'IF',
  'SUM',
] as const;

export const FORMULA_FUNCTION_BY_NAME: ReadonlyMap<string, FormulaFunction> = new Map(
  FORMULA_FUNCTIONS.map((item) => [item.name, item]),
);

export function getFormulaFunctionsByCategory(
  category: FormulaFunctionCategory,
): readonly FormulaFunction[] {
  return FORMULA_FUNCTIONS.filter((item) => item.category === category);
}
