import type { FormSchemaDocument } from '@evolyn.do/form/schema';

/** 无后端联调时用于验收移动填写、草稿恢复与提交动作的最小业务表单。 */
export const demoOrderSchema: FormSchemaDocument = {
  content: {
    type: 'form',
    layout: 'normal',
    items: [
      {
        widget: {
          type: 'text',
          widgetName: '_widget_order_no',
          fieldId: 'moborderno',
          enable: false,
          visible: true,
          allowBlank: true,
          placeholder: '系统生成无需填写',
          maxLength: 40,
        },
        label: '订单编号',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'text',
          widgetName: '_widget_creator',
          fieldId: 'mobcreator',
          enable: true,
          visible: true,
          allowBlank: false,
          placeholder: '请输入制单人',
          defaultValue: '@lee',
          maxLength: 30,
        },
        label: '制单人',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'datetime',
          widgetName: '_widget_order_date',
          fieldId: 'moborddate',
          enable: true,
          visible: true,
          allowBlank: false,
          format: 'date',
          placeholder: '请选择下单日期',
        },
        label: '下单日期',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'text',
          widgetName: '_widget_customer',
          fieldId: 'mobcustmer',
          enable: true,
          visible: true,
          allowBlank: false,
          placeholder: '请输入客户名称',
          maxLength: 80,
        },
        label: '客户名称',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'text',
          widgetName: '_widget_contact',
          fieldId: 'mobcontact',
          enable: true,
          visible: true,
          allowBlank: true,
          placeholder: '请输入联系人',
          maxLength: 40,
        },
        label: '联系人',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
    ],
    layout_fields: [],
    field_layout: [
      '_widget_order_no',
      '_widget_creator',
      '_widget_order_date',
      '_widget_customer',
      '_widget_contact',
    ],
    fieldShowRules: [],
    submitRule: 2,
    widget_submit_rules: {},
    validators: [],
    preSubmitConfirm: { enable: false, title: '确认提交', content: '请确认填写内容无误。' },
    formEvents: [],
    linkages: [],
    fieldFormulas: [],
  },
};
