import type { FormSchemaDocument } from '@evolyn.do/form/schema';

/** 移动宿主的最小验收 Schema；正式业务页面应从发布版本接口加载不可变快照。 */
export const runtimePreviewSchema: FormSchemaDocument = {
  content: {
    type: 'form',
    layout: 'normal',
    items: [
      {
        widget: {
          type: 'text',
          widgetName: '_widget_name',
          fieldId: 'mobname001',
          enable: true,
          visible: true,
          allowBlank: false,
          placeholder: '请输入申请人姓名',
          maxLength: 30,
        },
        label: '申请人',
        description: '用于验证必填、字数限制与错误定位。',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'combo',
          widgetName: '_widget_category',
          fieldId: 'mobcateg01',
          enable: true,
          visible: true,
          allowBlank: false,
          placeholder: '请选择申请类型',
          options: [
            { label: '采购申请', value: 'purchase' },
            { label: '用印申请', value: 'seal' },
            { label: '费用报销', value: 'expense' },
          ],
        },
        label: '申请类型',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'radiogroup',
          widgetName: '_widget_priority',
          fieldId: 'mobprior01',
          enable: true,
          visible: true,
          allowBlank: false,
          layout: 'horizontal',
          options: [
            { label: '普通', value: 'normal' },
            { label: '紧急', value: 'urgent' },
          ],
          defaultValue: 'normal',
        },
        label: '优先级',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'checkboxgroup',
          widgetName: '_widget_tags',
          fieldId: 'mobtags001',
          enable: true,
          visible: true,
          allowBlank: true,
          layout: 'horizontal',
          options: [
            { label: '需要审批', value: 'approval' },
            { label: '需要抄送', value: 'cc' },
            { label: '包含附件', value: 'attachment' },
          ],
          defaultValue: [],
        },
        label: '业务标签',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'number',
          widgetName: '_widget_days',
          fieldId: 'mobdays001',
          enable: true,
          visible: true,
          allowBlank: true,
          placeholder: '请输入预计处理天数',
          min: 1,
          max: 30,
          precision: 0,
          defaultValue: null,
        },
        label: '预计处理天数',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
      {
        widget: {
          type: 'textarea',
          widgetName: '_widget_reason',
          fieldId: 'mobreason1',
          enable: true,
          visible: true,
          allowBlank: false,
          placeholder: '请说明申请原因',
          maxLength: 300,
          autoHeight: true,
        },
        label: '申请原因',
        description: '',
        labelHidden: false,
        lineWidth: 12,
      },
    ],
    layout_fields: [],
    field_layout: [
      '_widget_name',
      '_widget_category',
      '_widget_priority',
      '_widget_tags',
      '_widget_days',
      '_widget_reason',
    ],
    fieldShowRules: [],
    submitRule: 2,
    widget_submit_rules: {},
    validators: [],
    preSubmitConfirm: {
      enable: true,
      title: '确认提交申请？',
      content: '请确认填写内容无误，提交后将进入业务处理流程。',
    },
    formEvents: [],
    linkages: [],
    fieldFormulas: [],
  },
};
