/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppsWidget: typeof import('./components/dashboard/widgets/AppsWidget.vue')['default']
    AuthLayout: typeof import('./components/auth/AuthLayout.vue')['default']
    BrandPanel: typeof import('./components/auth/BrandPanel.vue')['default']
    ChartsWidget: typeof import('./components/dashboard/widgets/ChartsWidget.vue')['default']
    DashboardCanvas: typeof import('./components/dashboard/DashboardCanvas.vue')['default']
    DashboardWidgetFrame: typeof import('./components/dashboard/DashboardWidgetFrame.vue')['default']
    DashboardWidgetHost: typeof import('./components/dashboard/DashboardWidgetHost.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTag: typeof import('element-plus/es')['ElTag']
    FavoritesWidget: typeof import('./components/dashboard/widgets/FavoritesWidget.vue')['default']
    GreetingWidget: typeof import('./components/dashboard/widgets/GreetingWidget.vue')['default']
    LocaleSwitch: typeof import('./components/auth/LocaleSwitch.vue')['default']
    OAuthLoginPanel: typeof import('./components/auth/OAuthLoginPanel.vue')['default']
    OnboardingWidget: typeof import('./components/dashboard/widgets/OnboardingWidget.vue')['default']
    PasswordLoginForm: typeof import('./components/auth/PasswordLoginForm.vue')['default']
    RegisterAccountStep: typeof import('./components/auth/RegisterAccountStep.vue')['default']
    RegisterProfileStep: typeof import('./components/auth/RegisterProfileStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutWidget: typeof import('./components/dashboard/widgets/ShortcutWidget.vue')['default']
    SmsLoginForm: typeof import('./components/auth/SmsLoginForm.vue')['default']
    TenantChoiceStep: typeof import('./components/auth/TenantChoiceStep.vue')['default']
    TodoWidget: typeof import('./components/dashboard/widgets/TodoWidget.vue')['default']
    TopNavigation: typeof import('./components/navigation/TopNavigation.vue')['default']
    WidgetPalette: typeof import('./components/dashboard/editor/WidgetPalette.vue')['default']
    WorkbenchDesignCanvas: typeof import('./components/dashboard/editor/WorkbenchDesignCanvas.vue')['default']
    WorkbenchEditorShell: typeof import('./components/dashboard/editor/WorkbenchEditorShell.vue')['default']
    WorkbenchEditorToolbar: typeof import('./components/dashboard/editor/WorkbenchEditorToolbar.vue')['default']
    WorkbenchEditorWidgetHost: typeof import('./components/dashboard/editor/WorkbenchEditorWidgetHost.vue')['default']
  }
}
