// 稳定业务错误码表（与后端 ADR-008 对齐，逐步扩充）：
// 消费方按 errCode 分支，禁止用 message 文本匹配（文案会随运营调整）
export const ERROR_CODES = {
  // 通用
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER: 'INTERNAL_SERVER',

  // 认证域（auth）
  AUTH_COOLDOWN: 'AUTH_COOLDOWN',
  AUTH_SMS_INVALID: 'AUTH_SMS_INVALID',
  AUTH_SMS_TOO_MANY_TRIES: 'AUTH_SMS_TOO_MANY_TRIES',
  AUTH_SMS_SCENE_INVALID: 'AUTH_SMS_SCENE_INVALID',
  AUTH_PHONE_INVALID: 'AUTH_PHONE_INVALID',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  AUTH_ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  AUTH_NOT_MEMBER: 'AUTH_NOT_MEMBER',
  AUTH_STALE_TENANT: 'AUTH_STALE_TENANT',
  AUTH_PASSWORD_DECRYPT_FAILED: 'AUTH_PASSWORD_DECRYPT_FAILED',

  // IAM 域
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  DUPLICATE_MEMBER: 'DUPLICATE_MEMBER',
  CROSS_TENANT_BINDING_REJECTED: 'CROSS_TENANT_BINDING_REJECTED',

  // 租户域
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  TENANT_FROZEN: 'TENANT_FROZEN',
  TENANT_DISABLED: 'TENANT_DISABLED',
  TENANT_CODE_DUPLICATED: 'TENANT_CODE_DUPLICATED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
