import {
  RiArchiveFill,
  RiBarChartBoxFill,
  RiBookmark3Fill,
  RiBriefcase4Fill,
  RiBuilding2Fill,
  RiCalendarCheckFill,
  RiCalendarTodoFill,
  RiCheckboxCircleFill,
  RiClipboardFill,
  RiContactsBook3Fill,
  RiCustomerService2Fill,
  RiDashboardFill,
  RiDatabase2Fill,
  RiFileChartFill,
  RiFileList3Fill,
  RiFileTextFill,
  RiFolder3Fill,
  RiGiftFill,
  RiGlobalFill,
  RiHome5Fill,
  RiInboxArchiveFill,
  RiLineChartFill,
  RiLinksFill,
  RiMapPin2Fill,
  RiMoneyCnyBoxFill,
  RiPriceTag3Fill,
  RiProductHuntFill,
  RiProjector2Fill,
  RiQuestionAnswerFill,
  RiRobot2Fill,
  RiRouteFill,
  RiServiceFill,
  RiSettings3Fill,
  RiShoppingBag3Fill,
  RiShoppingCart2Fill,
  RiStore2Fill,
  RiTeamFill,
  RiTrophyFill,
  RiUserStarFill,
  RiVipCrown2Fill,
  RiWallet3Fill,
} from '@remixicon/vue';
import { markRaw } from 'vue';
import type {
  EvolynIconPickerColorOption,
  EvolynIconPickerSystemIcon,
} from './EvolynIconPicker.types';

/** 静态导入避免把 Remix Icon 全量打入业务包。 */
export const defaultSystemIcons: EvolynIconPickerSystemIcon[] = [
  ['archive', '归档', RiArchiveFill],
  ['bookmark', '书签', RiBookmark3Fill],
  ['chart', '图表', RiBarChartBoxFill],
  ['briefcase', '公文包', RiBriefcase4Fill],
  ['building', '企业', RiBuilding2Fill],
  ['calendar-check', '日历完成', RiCalendarCheckFill],
  ['calendar-todo', '待办', RiCalendarTodoFill],
  ['check', '完成', RiCheckboxCircleFill],
  ['clipboard', '剪贴板', RiClipboardFill],
  ['contacts', '通讯录', RiContactsBook3Fill],
  ['service', '客服', RiCustomerService2Fill],
  ['dashboard', '仪表盘', RiDashboardFill],
  ['database', '数据', RiDatabase2Fill],
  ['report', '报表', RiFileChartFill],
  ['list', '列表', RiFileList3Fill],
  ['document', '文档', RiFileTextFill],
  ['folder', '文件夹', RiFolder3Fill],
  ['gift', '礼品', RiGiftFill],
  ['global', '全球', RiGlobalFill],
  ['home', '主页', RiHome5Fill],
  ['inbox', '收件箱', RiInboxArchiveFill],
  ['line-chart', '趋势图', RiLineChartFill],
  ['links', '连接', RiLinksFill],
  ['location', '位置', RiMapPin2Fill],
  ['money', '金额', RiMoneyCnyBoxFill],
  ['tag', '标签', RiPriceTag3Fill],
  ['product', '产品', RiProductHuntFill],
  ['project', '项目', RiProjector2Fill],
  ['question', '问答', RiQuestionAnswerFill],
  ['robot', '智能助手', RiRobot2Fill],
  ['route', '流程', RiRouteFill],
  ['service-center', '服务中心', RiServiceFill],
  ['settings', '设置', RiSettings3Fill],
  ['shopping-bag', '商品', RiShoppingBag3Fill],
  ['shopping-cart', '购物车', RiShoppingCart2Fill],
  ['store', '店铺', RiStore2Fill],
  ['team', '团队', RiTeamFill],
  ['trophy', '奖杯', RiTrophyFill],
  ['user-star', '明星成员', RiUserStarFill],
  ['vip', '会员', RiVipCrown2Fill],
  ['wallet', '钱包', RiWallet3Fill],
].map(([name, label, icon]) => ({ name, label, icon: markRaw(icon) }));

export const defaultIconColors: EvolynIconPickerColorOption[] = [
  { label: '金色', background: '#f7be54,#eda426' },
  { label: '红色', background: '#fd7d79,#ef5655' },
  { label: '绿色', background: '#64c871,#3bad4a' },
  { label: '青色', background: '#3ac1f2,#04a4de' },
  { label: '蓝色', background: '#80b1ff,#2b73f0' },
  { label: '紫色', background: '#8d76f5,#7358e8' },
];
