// 稳定业务错误码表（与后端 ADR-008 对齐，逐步扩充）：
// 消费方按 errCode 分支，禁止用 message 文本匹配（文案会随运营调整）。
// 错误值即请求层抛出的 ApiError.errCode 的取值域。
export const ERROR_CODES = {
  // 通用
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER: 'INTERNAL_SERVER',

  // 认证域（auth）
  AUTH_COOLDOWN: 'AUTH_COOLDOWN',
  AUTH_SMS_INVALID: 'AUTH_SMS_INVALID',
  AUTH_SMS_TOO_MANY_TRIES: 'AUTH_SMS_TOO_MANY_TRIES',
  AUTH_SMS_DAILY_LIMIT: 'AUTH_SMS_DAILY_LIMIT',
  AUTH_SMS_SCENE_INVALID: 'AUTH_SMS_SCENE_INVALID',
  AUTH_PHONE_INVALID: 'AUTH_PHONE_INVALID',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  AUTH_ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  AUTH_NOT_MEMBER: 'AUTH_NOT_MEMBER',
  AUTH_STALE_TENANT: 'AUTH_STALE_TENANT',
  AUTH_PASSWORD_DECRYPT_FAILED: 'AUTH_PASSWORD_DECRYPT_FAILED',
  AUTH_SESSION_INVALIDATED: 'AUTH_SESSION_INVALIDATED',
  AUTH_SESSION_REPLACED: 'AUTH_SESSION_REPLACED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_SMS_IP_LIMIT: 'AUTH_SMS_IP_LIMIT',
  AUTH_LOGIN_LOCKED: 'AUTH_LOGIN_LOCKED',
  AUTH_REVOKE_CHECK_FAILED: 'AUTH_REVOKE_CHECK_FAILED',
  AUTH_MFA_UNAVAILABLE: 'AUTH_MFA_UNAVAILABLE',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_MFA_CHALLENGE_EXPIRED: 'AUTH_MFA_CHALLENGE_EXPIRED',
  AUTH_MFA_CHALLENGE_TRIES_EXCEEDED: 'AUTH_MFA_CHALLENGE_TRIES_EXCEEDED',
  AUTH_MFA_ALREADY_ENABLED: 'AUTH_MFA_ALREADY_ENABLED',
  AUTH_REAUTH_REQUIRED: 'AUTH_REAUTH_REQUIRED',
  AUTH_REAUTH_LOGIN_REQUIRED: 'AUTH_REAUTH_LOGIN_REQUIRED',

  // IAM 域
  DUPLICATE_NAME: 'DUPLICATE_NAME',
  DUPLICATE_MEMBER: 'DUPLICATE_MEMBER',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  CROSS_TENANT_BINDING_REJECTED: 'CROSS_TENANT_BINDING_REJECTED',
  MEMBER_STATUS_INVALID: 'MEMBER_STATUS_INVALID',
  TENANT_CREATOR_STATUS_IMMUTABLE: 'TENANT_CREATOR_STATUS_IMMUTABLE',
  MEMBER_INVITATION_INVALID: 'MEMBER_INVITATION_INVALID',
  MEMBER_INVITATION_CONTACT_REQUIRED: 'MEMBER_INVITATION_CONTACT_REQUIRED',
  MEMBER_INVITATION_IMPORT_FILE_INVALID: 'MEMBER_INVITATION_IMPORT_FILE_INVALID',
  // 成员信息管理（字段配置/成员档案/邀请接受）
  MEMBER_FIELD_NOT_FOUND: 'MEMBER_FIELD_NOT_FOUND',
  MEMBER_FIELD_LOCKED: 'MEMBER_FIELD_LOCKED',
  MEMBER_FIELD_CONFIG_INVALID: 'MEMBER_FIELD_CONFIG_INVALID',
  MEMBER_FIELD_CONFIG_CONFLICT: 'MEMBER_FIELD_CONFIG_CONFLICT',
  MEMBER_PROFILE_INVALID: 'MEMBER_PROFILE_INVALID',
  MEMBER_INVITATION_ACCEPT_INVALID: 'MEMBER_INVITATION_ACCEPT_INVALID',
  // 权限中心-管理员模块（管理组）
  ADMIN_GROUP_NOT_FOUND: 'ADMIN_GROUP_NOT_FOUND',
  ADMIN_GROUP_NAME_INVALID: 'ADMIN_GROUP_NAME_INVALID',
  ADMIN_GROUP_DUPLICATE_NAME: 'ADMIN_GROUP_DUPLICATE_NAME',
  ADMIN_GROUP_BUILTIN_IMMUTABLE: 'ADMIN_GROUP_BUILTIN_IMMUTABLE',
  ADMIN_GROUP_LAST_ADMIN: 'ADMIN_GROUP_LAST_ADMIN',
  ADMIN_GROUP_SCOPE_MISMATCH: 'ADMIN_GROUP_SCOPE_MISMATCH',
  ADMIN_GROUP_CONFIG_INVALID: 'ADMIN_GROUP_CONFIG_INVALID',
  ADMIN_GROUP_MEMBER_INVALID: 'ADMIN_GROUP_MEMBER_INVALID',
  ADMIN_GROUP_TENANT_CREATOR_NOT_ALLOWED: 'ADMIN_GROUP_TENANT_CREATOR_NOT_ALLOWED',

  // 租户域
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',

  // 表单资产域（form，ADR-010）
  FORM_NOT_FOUND: 'FORM_NOT_FOUND',
  FORM_NAME_INVALID: 'FORM_NAME_INVALID',
  FORM_TYPE_INVALID: 'FORM_TYPE_INVALID',
  FORM_APP_INVALID: 'FORM_APP_INVALID',
  FORM_SCHEMA_INVALID: 'FORM_SCHEMA_INVALID',
  FORM_REVISION_CONFLICT: 'FORM_REVISION_CONFLICT',
  FORM_PUBLISH_UNSUPPORTED_FIELD: 'FORM_PUBLISH_UNSUPPORTED_FIELD',
  FORM_NOT_PUBLISHED: 'FORM_NOT_PUBLISHED',
  FORM_VERSION_CONFLICT: 'FORM_VERSION_CONFLICT',
  FORM_RECORD_INVALID: 'FORM_RECORD_INVALID',

  TENANT_FROZEN: 'TENANT_FROZEN',
  TENANT_DISABLED: 'TENANT_DISABLED',
  TENANT_CODE_DUPLICATED: 'TENANT_CODE_DUPLICATED',
  TENANT_NAME_INVALID: 'TENANT_NAME_INVALID',
  ACCOUNT_OWNS_TENANT: 'ACCOUNT_OWNS_TENANT',

  // 应用域（M2-A）
  APP_NAME_INVALID: 'APP_NAME_INVALID',
  APP_ICON_INVALID: 'APP_ICON_INVALID',
  APP_COLOR_INVALID: 'APP_COLOR_INVALID',
  APP_MEMBER_INVALID: 'APP_MEMBER_INVALID',
  APP_NOT_FOUND: 'APP_NOT_FOUND',
  APP_STATUS_INVALID: 'APP_STATUS_INVALID',
  APP_PROVISIONING: 'APP_PROVISIONING',
  APP_QUERY_INVALID: 'APP_QUERY_INVALID',
  APP_CURSOR_INVALID: 'APP_CURSOR_INVALID',

  // 版本信息域（一期）：与后端 edition/errors.go 对齐
  EDITION_TENANT_NOT_FOUND: 'EDITION_TENANT_NOT_FOUND',
  EDITION_PLAN_VERSION_NOT_FOUND: 'EDITION_PLAN_VERSION_NOT_FOUND',
  EDITION_PLAN_VERSION_NOT_GRANTABLE: 'EDITION_PLAN_VERSION_NOT_GRANTABLE',
  EDITION_GRANT_INVALID: 'EDITION_GRANT_INVALID',
  EDITION_OVERRIDE_INVALID: 'EDITION_OVERRIDE_INVALID',
  EDITION_STORAGE_LIMIT_INVALID: 'EDITION_STORAGE_LIMIT_INVALID',
  EDITION_SUBSCRIPTION_NOT_FOUND: 'EDITION_SUBSCRIPTION_NOT_FOUND',

  // 应用菜单域（M2-菜单）：MENU_INVALID 已随只读接口启用，其余随分组/
  // 重排管理接口（M2-菜单-3）落地启用，与后端 application/errors.go 对齐
  APP_MENU_NAME_INVALID: 'APP_MENU_NAME_INVALID',
  APP_MENU_NOT_FOUND: 'APP_MENU_NOT_FOUND',
  APP_MENU_PARENT_INVALID: 'APP_MENU_PARENT_INVALID',
  APP_MENU_TARGET_INVALID: 'APP_MENU_TARGET_INVALID',
  APP_MENU_DEPTH_EXCEEDED: 'APP_MENU_DEPTH_EXCEEDED',
  APP_MENU_ORDER_INVALID: 'APP_MENU_ORDER_INVALID',
  APP_MENU_VERSION_CONFLICT: 'APP_MENU_VERSION_CONFLICT',
  APP_MENU_INVALID: 'APP_MENU_INVALID',

  // 产品中心域（一期）：与后端 tenantproduct/errors.go 对齐；
  // DISABLED/ACCESS_DENIED 预留给产品受保护入口
  TENANT_PRODUCT_NOT_FOUND: 'TENANT_PRODUCT_NOT_FOUND',
  TENANT_PRODUCT_SCOPE_INVALID: 'TENANT_PRODUCT_SCOPE_INVALID',
  TENANT_PRODUCT_SCOPE_EMPTY: 'TENANT_PRODUCT_SCOPE_EMPTY',
  TENANT_PRODUCT_MEMBER_INVALID: 'TENANT_PRODUCT_MEMBER_INVALID',
  TENANT_PRODUCT_DEPARTMENT_INVALID: 'TENANT_PRODUCT_DEPARTMENT_INVALID',
  TENANT_PRODUCT_REVISION_CONFLICT: 'TENANT_PRODUCT_REVISION_CONFLICT',
  TENANT_PRODUCT_DISABLED: 'TENANT_PRODUCT_DISABLED',
  TENANT_PRODUCT_ACCESS_DENIED: 'TENANT_PRODUCT_ACCESS_DENIED',

  // 消息中心域（P1/P2）：与后端 notification/errors.go 对齐；分页游标失效
  // 提示刷新，设置冲突（revision 过期）提示重载，联系人被引用先移除引用
  NOTIFICATION_CATEGORY_UNKNOWN: 'NOTIFICATION_CATEGORY_UNKNOWN',
  NOTIFICATION_EVENT_UNKNOWN: 'NOTIFICATION_EVENT_UNKNOWN',
  NOTIFICATION_CURSOR_INVALID: 'NOTIFICATION_CURSOR_INVALID',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_SETTINGS_CONFLICT: 'NOTIFICATION_SETTINGS_CONFLICT',
  NOTIFICATION_CHANNEL_NOT_SUPPORTED: 'NOTIFICATION_CHANNEL_NOT_SUPPORTED',
  NOTIFICATION_CHANNEL_REQUIRED: 'NOTIFICATION_CHANNEL_REQUIRED',
  NOTIFICATION_CHANNEL_UNAVAILABLE: 'NOTIFICATION_CHANNEL_UNAVAILABLE',
  NOTIFICATION_RECIPIENT_INVALID: 'NOTIFICATION_RECIPIENT_INVALID',
  NOTIFICATION_RECIPIENT_NOT_FOUND: 'NOTIFICATION_RECIPIENT_NOT_FOUND',
  NOTIFICATION_RECIPIENT_IN_USE: 'NOTIFICATION_RECIPIENT_IN_USE',
  NOTIFICATION_RECIPIENT_LIMIT_EXCEEDED: 'NOTIFICATION_RECIPIENT_LIMIT_EXCEEDED',

  // 流程引擎域（ADR-012）：Phase 0 预留分段（见 internal/platform/workflow/doc.go），
  // 后端稳定码随 Phase 1 Definition Engine 落地；草稿乐观锁冲突按
  // WORKFLOW_DEFINITION_INVALID 细分提示，解析不到审批人提示联系管理员
  WORKFLOW_DEFINITION_INVALID: 'WORKFLOW_DEFINITION_INVALID',
  WORKFLOW_VERSION_NOT_PUBLISHED: 'WORKFLOW_VERSION_NOT_PUBLISHED',
  WORKFLOW_INSTANCE_ALREADY_RUNNING: 'WORKFLOW_INSTANCE_ALREADY_RUNNING',
  WORKFLOW_INSTANCE_NOT_RUNNING: 'WORKFLOW_INSTANCE_NOT_RUNNING',
  WORKFLOW_TASK_NOT_PENDING: 'WORKFLOW_TASK_NOT_PENDING',
  WORKFLOW_TASK_FORBIDDEN: 'WORKFLOW_TASK_FORBIDDEN',
  WORKFLOW_ACTION_NOT_ALLOWED: 'WORKFLOW_ACTION_NOT_ALLOWED',
  WORKFLOW_EXPRESSION_INVALID: 'WORKFLOW_EXPRESSION_INVALID',
  WORKFLOW_ASSIGNEE_NOT_FOUND: 'WORKFLOW_ASSIGNEE_NOT_FOUND',
  WORKFLOW_FORM_VERSION_INVALID: 'WORKFLOW_FORM_VERSION_INVALID',
  WORKFLOW_FORM_FIELD_FORBIDDEN: 'WORKFLOW_FORM_FIELD_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** errCode 是否为表中已知码（未知码按通用失败兜底） */
export function isKnownErrorCode(errCode: string | undefined): errCode is ErrorCode {
  return !!errCode && Object.values(ERROR_CODES).includes(errCode as ErrorCode);
}
